def build_initial_runtime_objects(
    *,
    queue_module,
    threading_module,
    deque_factory,
    random_module,
    concurrent_futures_module,
    updates_event_buffer_max,
    default_notify_reply_templates,
    default_dm_templates,
    dm_llm_rewrite_dedupe_size,
    notification_refresh_interval_min_sec,
    notification_refresh_interval_max_sec,
):
    return {
        'monitor_active': False,
        'monitor_tasks': [],
        'processed_users': set(),
        'pending_results': [],
        'history_ids': set(),
        'msg_queue': queue_module.Queue(),
        'updates_event_seq': 0,
        'updates_event_buffer': deque_factory(maxlen=updates_event_buffer_max),
        'notify_server_audio_queue': queue_module.Queue(),
        'notify_server_audio_thread': None,
        'notify_server_audio_thread_lock': threading_module.Lock(),
        'notify_server_audio_last_error': '',
        'notify_server_audio_last_ok_at': 0.0,
        'notify_server_audio_queue_size': 0,
        'global_token': '',
        'delegated_account': '',
        'delegated_enabled': False,
        'delegated_account_active': '',
        'delegated_switch_ok': False,
        'headless_mode': True,
        'data_lock': threading_module.Lock(),
        'browser_lock': threading_module.Lock(),
        'browser_init_lock': threading_module.Lock(),
        'tab_lock': threading_module.Lock(),
        'notification_monitoring': False,
        'global_browser': None,
        'global_browser_dir': None,
        'browser_initialized': False,
        'browser_force_temp_profile': False,
        'reply_action_lock': threading_module.Lock(),
        'reply_rate_limit_lock': threading_module.Lock(),
        'reply_work_tab': None,
        'reply_work_tab_lock': threading_module.Lock(),
        'reply_flow_state_lock': threading_module.Lock(),
        'reply_flow_active': False,
        'dm_passcode_warmed': False,
        'dm_passcode_lock': threading_module.Lock(),
        'dm_rate_limit_lock': threading_module.Lock(),
        'dm_critical_lock': threading_module.RLock(),
        'dm_critical_state_lock': threading_module.Lock(),
        'dm_critical_depth': 0,
        'dm_critical_started_at': 0.0,
        'dm_critical_last_skip_log_ts': 0.0,
        'dm_critical_last_timeout_warn_ts': 0.0,
        'reply_metrics_lock': threading_module.Lock(),
        'notify_reply_templates': list(default_notify_reply_templates),
        'dm_message_templates': list(default_dm_templates),
        'last_reply_action_ts': 0.0,
        'last_dm_action_ts': 0.0,
        'last_reply_prepare_refresh_ts': 0.0,
        'reply_outcome_recent': deque_factory(maxlen=50),
        'reply_failure_streak': 0,
        'reply_handle_failures': {},
        'notify_dm_user_cooldown': {},
        'notify_dm_user_cooldown_lock': threading_module.Lock(),
        'dm_unavailable_cache': {},
        'dm_unavailable_cache_lock': threading_module.Lock(),
        'llm_filter_cache': {},
        'llm_filter_cache_lock': threading_module.Lock(),
        'dm_llm_rewrite_history': deque_factory(maxlen=dm_llm_rewrite_dedupe_size),
        'dm_llm_rewrite_lock': threading_module.Lock(),
        'task_executor': concurrent_futures_module.ThreadPoolExecutor(max_workers=10),
        'notification_tab': None,
        'notification_tab_lock': threading_module.Lock(),
        'monitor_thread': None,
        'monitor_thread_lock': threading_module.Lock(),
        'content_dedupe': {},
        'notification_refresh_interval': random_module.uniform(
            notification_refresh_interval_min_sec,
            notification_refresh_interval_max_sec,
        ),
        'notification_last_refresh_at': 0.0,
        'notification_disconnect_streak': 0,
        'notification_empty_article_streak': 0,
    }
